language: bash
services: docker

env:
  - GLIBC_VERSION=2.29-r0

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --build-arg GLIBC_VERSION=$GLIBC_VERSION -t cda0/alpine-glibc .
  - docker tag cda0/alpine-glibc:latest
  - docker push cda0/alpine-glibc:$GLIBC_VERSION
  - docker push cda0/alpine-glibc:latest

